platform :ios, "9.0"
inhibit_all_warnings!
use_frameworks!

target 'demo' do

    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'MJRefresh’
    pod 'Masonry'
    pod 'QMUIKit'
    pod 'YYKit'
    pod 'MMKV'

end
